package tcc.entra21.SeamSmart.util;

public enum Tamanho {

	BEBE_P, BEBE_M, BEBE_G, BEBE_GG, 
	INFANTIL_1, INFANTIL_2, INFANTIL_3, INFANTIL_4, INFANTIL_6, INFANTIL_8, INFANTIL_10, INFANTIL_12, INFANTIL_14, INFANTIL_, 
	ADULTO_P, ADULTO_M, ADULTO_G, ADULTO_GG, ADULTO_XG, ADULTO_XGG, ADULTO_XXG
	
}
